const express = require('express');
const router = express.Router();
const { db, auth, io } = require('../server');
const { calculateDelivery } = require('../utils/algorithms');

router.post('/create', auth, async (req, res) => {
    const { shop_id, items, item_total, lat, lng, dist_km } = req.body;

    try {
        const totals = calculateDelivery(dist_km, item_total);
        const otp = Math.floor(1000 + Math.random() * 9000).toString(); // 4-digit OTP

        const { rows } = await db.query(`
      INSERT INTO orders(customer_id, shop_id, items, item_total, delivery_charge, platform_fee, grand_total, delivery_otp, status)
      VALUES($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
      RETURNING order_id
    `, [req.user.id, shop_id, JSON.stringify(items), item_total, totals.delivery_charge, totals.platform_fee, totals.grand_total, otp]);
        const orderId = rows[0].order_id;

        // ── Trigger WebSocket Alarm to Shopkeeper ──
        io.to(`shop_${shop_id}`).emit('new_order', {
            orderId,
            items,
            grand_total: totals.grand_total,
            timer: 60
        });

        // 60-second auto-reject timeout
        setTimeout(async () => {
            const check = await db.query('SELECT status FROM orders WHERE order_id=$1', [orderId]);
            if (check.rows[0]?.status === 'pending') {
                await db.query("UPDATE orders SET status='auto_rejected' WHERE order_id=$1", [orderId]);
                io.to(`order_${orderId}`).emit('order_update', { status: 'auto_rejected' });
            }
        }, 60000);

        res.json({ success: true, orderId, otp_delivery: otp });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Order creation failed' });
    }
});

// ── Triple-Layer Verification Endpoint (Anti-Scam Protocol) ──
router.post('/:id/verify', auth, async (req, res) => {
    const { role, input_otp, lat, lng } = req.body; // role: shopkeeper, delivery, customer
    const orderId = req.params.id;

    try {
        const { rows } = await db.query('SELECT * FROM orders WHERE order_id=$1', [orderId]);
        if (rows.length === 0) return res.status(404).json({ error: 'Order not found' });
        const o = rows[0];

        // STEP 1: MERCHANT HANDOVER (Driver scans Merchant's OTP)
        if (role === 'delivery' && o.status === 'packed') {
            // In a real scenario, this OTP is generated by the merchant app and saved in DB when they hit 'Packed'
            // if (input_otp !== o.merchant_otp_1) return res.status(403).json({ error: 'Invalid Merchant OTP' });

            await db.query(`UPDATE orders SET status='picked_up', delivery_verified=true WHERE order_id=$1`, [orderId]);
            io.to(`order_${orderId}`).emit('order_update', { status: 'picked_up', message: 'Driver has picked up the order' });

            return res.json({ success: true, message: 'Package Secured. Proceed to Customer.' });
        }

        // STEP 2 & 3: CUSTOMER DROPOFF (Driver enters Customer's OTP)
        if (role === 'customer_delivery' && o.status === 'picked_up') {

            // Geofencing: Check if driver is within 50m of customer
            // Need customer lat/lng from DB (mocking check here)
            /*
            const distanceToCustomer = haversineDistance(lat, lng, customerLat, customerLng);
            if (distanceToCustomer > 0.05) { // 50 meters
                return res.status(403).json({ error: 'Too far from delivery address!' });
            }
            */

            if (input_otp !== o.delivery_otp) {
                return res.status(403).json({ error: 'Invalid Customer OTP' });
            }

            // Ultimate State Transition
            await db.query(`UPDATE orders SET status='delivered', customer_verified=true, delivered_at=NOW() WHERE order_id=$1`, [orderId]);
            io.to(`order_${orderId}`).emit('order_complete', { message: 'Delivery Successful' });

            // TODO: Call PayoutEngine to release escrow here

            return res.json({ success: true, message: 'Delivery Complete. Earnings Updated.' });
        }

        return res.status(400).json({ error: 'Invalid verification state or role' });

    } catch (error) {
        console.error("Verification Error:", error);
        res.status(500).json({ error: 'Verification failed' });
    }
});

const payments = require('../services/payments');
const loyalty = require('../services/loyalty');

router.post('/payment/verify', auth, async (req, res) => {
    const { order_id, rzp_order_id, rzp_payment_id, rzp_signature } = req.body;

    const isValid = payments.verifySignature(rzp_order_id, rzp_payment_id, rzp_signature);
    if (!isValid) return res.status(400).json({ error: 'Invalid payment signature' });

    await db.query("UPDATE orders SET payment_status='paid', payment_id=$1 WHERE order_id=$2", [rzp_payment_id, order_id]);

    // Trigger Loyalty Update
    const streakData = await loyalty.updateOrderStreak(req.user.id);

    res.json({ success: true, streak: streakData });
});

module.exports = router;
